language: php

php:
  - 5.5

before_install:
  - sudo pwd
  - sudo apt-get update
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

before_script:
  - export MINK_EXTENSION_PARAMS='base_url=http://localhost/app_dev.php/'
  - composer self-update
  - composer install --prefer-source --no-interaction
  - chmod -R 777 app/cache app/logs
  - app/console cache:warmup --env=dev
  - chmod -R 777 app/cache app/logs
  - sleep 5

script:
  - bin/behat --stop-on-failure --verbose